version: "3.7"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/001_products.js:/docker-entrypoint-initdb.d/001_products.js:ro
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: node-task
      MONGO_INITDB_ROOT_PASSWORD: node-task
      MONGO_INITDB_DATABASE: node-task
    restart: unless-stopped

volumes:
  mongo-data:
  mongo-config:
